import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/TopBar";
import {LeftSideBar, RightSideBar} from "@/components/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopBar userName="sam" />
        <div className="flex flex-row width-[100%]">
          <LeftSideBar />
          {children}
          <RightSideBar />
        </div>
      </body>
    </html>
  );
}
