import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/TopBar";
import { LeftSideBar, RightSideBar } from "@/components/SideBar";
import nextAuth, { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import NextAuthProvider from '@/providers/NextAuthProvider'
import ReduxProvider from '@/redux/ReduxProvider'
import getRestaurants from "@/libs/getRestaurants";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)
  const restaurant = getRestaurants();

  if (session) {
    console.log("session:", session.user.name);
  } else {
    console.log("session: no session");
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <TopBar userName={session? session.user.name: "whoami" } />

        <div className="flex flex-row">
          <ReduxProvider>
          <NextAuthProvider session={session}>
            <LeftSideBar />
            {children}
            <RightSideBar RestaurantJson={restaurant} />
          </NextAuthProvider>
          </ReduxProvider>
        </div>
      </body>
    </html>
  );
}
