@startuml Payment (GET One)

header Get One Payment Sequence Diagram
footer Page 1 of 5
title "Payment (GET One)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:Payments" as routerPayments
participant "<<controllers>>\n:Payments" as controllersPayments
participant "<<model>>\n:Payment" as modelPayments
database "<<MongoDB>>\n:Payments" as PaymentDatabase

client->server ++:req.post('/Payments/:PaymentId')
server->routerPayments ++:app.use('/api/v1/Payments/:id', Payment);
routerPayments -> controllersPayments ++:getPayments()
controllersPayments->modelPayments ++:getPayment(req.body)
modelPayments ->PaymentDatabase ++: PaymentSchema
PaymentDatabase --> modelPayments --: Payment
controllersPayments <-- modelPayments --:Payment
controllersPayments->client --:response

@enduml