@startuml Payment (GET ALL)

header GET ALL Payment Sequence Diagram
footer Page 1 of 5
title "Payment (GET ALL)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:Payments" as routerPayments
participant "<<controllers>>\n:Payments" as controllersPayments
participant "<<model>>\n:Payment" as modelPayments
database "<<MongoDB>>\n:Payments" as PaymentDatabase

client->server ++:req.post('/Payments')
server->routerPayments ++:app.use('/api/v1/Payments', Payment);
routerPayments -> controllersPayments ++:getPayments()
controllersPayments->modelPayments ++: getPayments(req.body)
modelPayments ->PaymentDatabase ++: PaymentSchema
PaymentDatabase --> modelPayments --: Payment
controllersPayments <-- modelPayments --:Payment
controllersPayments->client --:response

@enduml