@startuml Restaurant (GET One)

header Get One Restaurant Sequence Diagram
footer Page 1 of 5
title "Restaurant (GET One)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:restaurants" as routerRestaurants
participant "<<controllers>>\n:restaurants" as controllersRestaurants
participant "<<model>>\n:restaurant" as modelRestaurants
database "<<MongoDB>>\n:restaurants" as RestaurantDatabase

client->server ++:req.post('/restaurants/:restaurantId')
server->routerRestaurants ++:app.use('/api/v1/restaurants/:id', restaurant);
routerRestaurants -> controllersRestaurants ++:getRestaurants()
controllersRestaurants->modelRestaurants ++:getRestaurant(req.body)
modelRestaurants ->RestaurantDatabase ++: RestaurantSchema
RestaurantDatabase --> modelRestaurants --: Restaurant
controllersRestaurants <-- modelRestaurants --:Restaurant
controllersRestaurants->client --:response

@enduml